mywebsite_project/urls.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------
"""

from django.urls import include, path

from . import views

app_name = 'project'

urlpatterns = [
    path('', views.ProjectListView.as_view(), name='projects'),
    path('manual', views.manual, name='project-manual'),
    path('<slug:slug>', views.ProjectDetailView.as_view(), name='project-detail'),
]

test_website/urls.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------

Website URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

import os

from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.db.utils import OperationalError
from django.urls import include, path, re_path
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog

import menu
from filebrowser.sites import site
from mywebsite_home import views as homeviews

urlpatterns = [
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/mywebsite/img/default/favicon.gif')),
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('qr/', include('django_otp.urls')),  # enable QRcode for 2FA
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),  # for hitcounts built-in AJAX post view
    path('captcha/', include('captcha.urls')),  # for captcha URLS
]

# handle language prefix in URL patterns
try:
    urlpatterns += i18n_patterns(
        path('tinymce/', include('tinymce.urls')),
        path('admin/filebrowser/', site.urls),
        # added custom view, see http://www.beardygeek.com/2010/03/adding-views-to-the-django-admin/
        path('admin/manual/', homeviews.manual, name='admin-manual'),
        path('admin/doc/', include('django.contrib.admindocs.urls')),
        path('admin/', admin.site.urls),
        # added javascript translation support, see
        # https://docs.djangoproject.com/en/dev/topics/i18n/translation/#internationalization-in-javascript-code
        path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
        # added website modules
        path('', include('mywebsite_home.urls', namespace='home')),
        path('projects/', include('mywebsite_project.urls', namespace='project')),
        path('blog/', include('mywebsite_blog.urls', namespace='blog')),
        prefix_default_language=False
    )
except OperationalError:
    # happens when db doesn't exist yet, views.py should be importable without this side effect
    pass

# serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=os.path.join(settings.BASE_DIR, 'static'))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


@classmethod
def load_menus(c):
    """
    load_menus loads the menu.py file from test_website.
    """

    # we don't need to do this more than once
    if c.loaded:
        return

    try:
        __import__('test_website.menus', fromlist=['menu', ])
    except ImportError:
        pass

    c.loaded = True


# override menu.Menu.load_menus with our own method, to load test_website.menus instead
menu.Menu.load_menus = load_menus

mywebsite_project/models.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------
"""

from django.db import models
from django.urls import reverse
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from parler.models import TranslatableModel, TranslatedFields
from tinymce.models import HTMLField

# Define states for field 'state'
BLUE_STATE = 0
YELLOW_STATE = 1
GREEN_STATE = 2
STATUS_CHOICES = (
    (BLUE_STATE, 'No working activities'),
    (YELLOW_STATE, 'Work in progress'),
    (GREEN_STATE, 'Work completed'),
)


# Hint: Making existing fields translatable,
# see https://django-parler.readthedocs.io/en/latest/advanced/migrating.html
class Project(TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(max_length=140),
        description=HTMLField(default='')
    )
    date = models.DateField(default=now)
    code_repository = models.CharField(max_length=140, default='')
    language = models.CharField(max_length=80)
    slug = models.SlugField(max_length=255, editable=True, unique=True, db_index=True, default=None, blank=True)

    class Meta:
        db_table = 'project_project'
        verbose_name = _('Project')
        verbose_name_plural = _('Projects')

    def __unicode__(self):
        if self.language_code:
            return self.title
        else:
            return '{} (ID: {})'.format(self.__class__.__name__, self.pk)

    def __str__(self):
        if self.language_code:
            return self.title
        else:
            return '{} (ID: {})'.format(self.__class__.__name__, self.pk)

    def get_absolute_url(self):
        return reverse('project', kwargs={'slug': self.slug, 'pk': self.pk})


# Hint: Making existing fields translatable,
# see https://django-parler.readthedocs.io/en/latest/advanced/migrating.html
class Milestone(TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(max_length=140)
    )
    duedate = models.DateField(default=now)
    project = models.ForeignKey('Project', on_delete=models.CASCADE, related_name="milestones")
    state = models.IntegerField(choices=STATUS_CHOICES, default=0)

    class Meta:
        db_table = 'project_milestone'
        verbose_name = _('Milestone')
        verbose_name_plural = _('Milestones')

    def __unicode__(self):
        if self.language_code:
            return '{}: {}'.format(self.project, self.title)
        else:
            return '{}: {} (ID: {})'.format(self.project, self.__class__.__name__, self.pk)

    def __str__(self):
        if self.language_code:
            return '{}: {}'.format(self.project, self.title)
        else:
            return '{}: {} (ID: {})'.format(self.project, self.__class__.__name__, self.pk)


# Hint: Making existing fields translatable,
# see https://django-parler.readthedocs.io/en/latest/advanced/migrating.html
class WorkItem(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=140),
        description=HTMLField(default='')
    )
    date = models.DateField(default=now)
    milestone = models.ForeignKey('Milestone', on_delete=models.CASCADE, related_name="workitems")
    state = models.IntegerField(choices=STATUS_CHOICES, default=0)

    class Meta:
        db_table = 'project_workitem'
        verbose_name = _('WorkItem')
        verbose_name_plural = _('WorkItems')

    def __unicode__(self):
        if self.language_code:
            return self.name
        else:
            return '{} (ID: {})'.format(self.__class__.__name__, self.pk)

    def __str__(self):
        if self.language_code:
            return self.name
        else:
            return '{} (ID: {})'.format(self.__class__.__name__, self.pk)

mywebsite_project/forms.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------
"""

from django import forms
from mywebsite.utils.widgets import TinyMCEWidget
from parler.forms import TranslatableModelForm

from . import models


class ProjectAdminForm(TranslatableModelForm):
    description = forms.CharField(widget=TinyMCEWidget(
        attrs={'cols': 30, 'rows': 10}
    ))

    class Meta:
        model = models.Project
        exclude = {}

    def __init__(self, *args, **kwargs):
        super(ProjectAdminForm, self).__init__(*args, **kwargs)


class WorkItemAdminForm(TranslatableModelForm):
    description = forms.CharField(widget=TinyMCEWidget(
        attrs={'cols': 30, 'rows': 10}
    ))

    class Meta:
        model = models.WorkItem
        exclude = {}

    def __init__(self, *args, **kwargs):
        super(WorkItemAdminForm, self).__init__(*args, **kwargs)

mywebsite_project/views.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------
"""

from django.shortcuts import render
from django.views import generic

from .models import Project


class ProjectListView(generic.ListView):
    model = Project
    context_object_name = 'project_list'
    template_name = 'project/project_list.html'
    paginate_by = 5

    def get_queryset(self):
        queryset = super(ProjectListView, self).get_queryset()
        # standard filter
        queryset = queryset.active_translations().distinct().all().order_by('-date')
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        return context


class ProjectDetailView(generic.DetailView):
    context_object_name = 'project'
    template_name = 'project/project.html'
    model = Project

    def get_context_data(self, **kwargs):
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        return context


def manual(request):
    return render(request, 'project/project_manual.html')

mywebsite_project/templates/project/project.html
{% extends 'home/base.html' %}
{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


{% load i18n static %}

{% block content %}
<section id="content">
    <div class="article-blog single">
        <h1>{% trans "PROJECT_TITLE" %}: {{ project.title }}</h1>
        <div class="separator"></div>
        <div class="card text-white bg-light mb-3" style="background-color: #252525 !important; width: 85%;">
            <div class="card-header">
                <dd class="card-text create">
                    <span data-toggle="tooltip"
                        title='{% trans "PROJECT_CREATION_DATE" %}'>{{ project.date|date:"d M Y" }}</span>
                </dd>
            </div>
            <div class="card-body">
                <p class="card-text">{{ project.description|safe }}</p>
                <dd class="card-text language">
                    <span data-toggle="tooltip"
                        title='{% trans "PROJECT_CODE_LANGUAGE" %}'>{{ project.language }}</span>
                </dd>
                <dd class="card-text bookmark">
                    <a class="text-white" href="{{ project.code_repository }}">{{ project.code_repository }}</a>
                </dd>
            </div>
        </div>
        <div class="separator"></div>
        <h2 class="article-header-blog">Road
            <span style="color: #ce9178;">map</span>
        </h2>
        <div class="separator"></div>
        <div class="content-text">
            <div class="row">
                <div class="col-md-12">
                    <div id="project-milestone" class="cd-container">
                        {% for milestone in project.milestones.all %}
                        <div class="project-milestone-block">
                            <div data-toggle="tooltip" title='{% trans "PROJECT_DUEDATE" %}: {{ milestone.duedate }}'>
                                {% if milestone.state == 2 %}
                                <div class="project-milestone-img cd-green"></div>
                                {% endif %} {% if milestone.state == 1 %}
                                <div class="project-milestone-img cd-yellow"></div>
                                {% endif %} {% if milestone.state == 0 %}
                                <div class="project-milestone-img cd-blue"></div>
                                {% endif %}
                            </div>
                            <div class="project-milestone-content">
                                <h2>
                                    <a data-toggle="collapse" href="#collapseExample-{{milestone.pk}}" role="button"
                                        aria-expanded="false" aria-controls="collapseExample-{{milestone.pk}}">
                                        {{ milestone.title }}
                                    </a>
                                </h2>
                                <div class="collapse" id="collapseExample-{{milestone.pk}}">
                                    <div class="milestone-workitem-block" style="text-align: left !important;">
                                        {% if milestone.workitems.all %} {% for workitem in milestone.workitems.all %}
                                        <dd class="card-text category-name">
                                            <span data-toggle="tooltip"
                                                title="{{ workitem.date }} / {{ workitem.description|striptags|safe }}">{{ workitem.name }}</span>
                                        </dd>
                                        {% endfor %} {% else %}
                                        <span>{% trans "PROJECT_NO_WORKITEMS" %}</span>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

mywebsite_project/templates/project/project_list.html
{% extends 'home/base.html' %}
{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


{% load i18n static %}

{% block content %}
<section id="content">
    <div class="separator"></div>
    <div class="article-list">
        {% for project in project_list %}
        <div class="article-blog post">
            <div class="meta">
                {{ project.date|date:"d M Y" }} / {% trans "PROJECT_CODE_LANGUAGE" %}: {{ project.language }}
            </div>
            <h2 class="article-header-blog">
                <a href="{% url 'project:project-detail' slug=project.slug %}">
                    {{ project.title }}
                </a>
            </h2>
            <div class="teaser">
                {{ project.description|safe }}
            </div>
            <h6 class="more">
                <a href="{% url 'project:project-detail' slug=project.slug %}">
                    {% trans "ARTICLE_LIST_READ_MORE" %}
                </a>
            </h6>
        </div>
        {% endfor %}
    </div>
    {% block pagination %} {% if is_paginated %}
    <div class="pagination">
        <span class="page-links">
            {% if page_obj.has_previous %}
            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">{% trans "PAGE_PREV" %}</a>
            {% endif %}
            <span class="page-current">
                {% trans "PAGE_TEXT1" %} {{ page_obj.number }} {% trans "PAGE_TEXT2" %}
                {{ page_obj.paginator.num_pages }}
            </span> {% if page_obj.has_next %}
            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">{% trans "PAGE_NEXT" %}</a> {% endif %}
        </span>
    </div>
    {% endif %} {% endblock %}
</section>
{% endblock %}

mywebsite_project/templates/project/project_manual.html
{% extends 'home/base.html' %}
{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


{% load i18n static %}

{% block extrastyle %}
<style>
    h2 {
        margin-bottom: 30px;
    }

    h3,
    h4,
    h5,
    h6 {
        margin-top: 50px;
        margin-bottom: 30px;
    }

    .hljs {
        background-color: #DDD;
        width: 98%;
        -webkit-box-shadow: 3px 8px 6px -6px black;
        -moz-box-shadow: 3px 8px 6px -6px black;
        box-shadow: 3px 8px 6px -6px black;
    }

</style>
{% endblock %}


{% block content %}
<section id="content">
    <div class="article-blog single">
        <h1 class="article-header-blog">
            {% trans "Manual" %}
        </h1>
        <div class="content-text">
            {% get_current_language as LANGUAGE_CODE %}
            {% if LANGUAGE_CODE == 'de' %}
            {% include 'admin_doc/MANUAL_DE.html' %}
            {% else %}
            {% include 'admin_doc/MANUAL_EN.html' %}
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}